"""first waistbeads table

Revision ID: 6ea2cb8ccd52
Revises: 270d62503112
Create Date: 2022-06-07 19:39:46.342395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea2cb8ccd52'
down_revision = '270d62503112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table('waistbeads',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('beader_id', sa.Integer(), nullable=False),
    # sa.Column('bead_img_url', sa.String(length=255), nullable=False),
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('price', sa.Float(), nullable=False),
    # sa.Column('description', sa.Text(length=255), nullable=True),
    # sa.Column('in_stock', sa.Boolean(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['beader_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('waistbeads')
    pass
    # ### end Alembic commands ###
