"""empty message

Revision ID: 61af583af30e
Revises: bfdf5d212519
Create Date: 2022-06-09 11:03:54.500162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61af583af30e'
down_revision = 'bfdf5d212519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('waistbeads_name_key', 'waistbeads', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('waistbeads_name_key', 'waistbeads', ['name'])
    # ### end Alembic commands ###
